[project]
name = "mlops-imdb-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cookiecutter>=2.6.0",
    "dagshub>=0.6.7",
    "mlflow>=3.10.0",
    "pipreqs>=0.4.13",
]
