name: CI Pipleline

on: push

jobs:
    project-testing:
        runs-on: ubuntu-latest

        steps:
            - name: checkout-code
              uses: actions/checkout@v3

            - name: setup python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.13.7"

            - name: Cache pip dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: install dependencies
              run: |
                  pip install -r requirements.txt

            - name: run pipeline
              env:
                  IMDB_TOKEN: ${{ secrets.IMDB_TOKEN}}
              run: |
                  dvc repro

            - name: Run model tests
              env:
                  IMDB_TOKEN: ${{ secrets.IMDB_TOKEN }}
              run: |
                  python -m unittest tests/test_model.py

            - name: Promote model to production
              if: success()
              env:
                  IMDB_TOKEN: ${{ secrets.IMDB_TOKEN }}
              run: python scripts/promote_model.py

            - name: Run Flask app tests
              if: success()
              env:
                  IMDB_TOKEN: ${{ secrets.IMDB_TOKEN }}
              run: python -m unittest tests/test_flask_app.py
